language: python
python:
  - "3.5"
install: "pip install -e . && FLASK_APP=iis/__init__.py IIS_FLASK_SETTINGS=../configuration/development.py flask db upgrade"
script: "IIS_FLASK_SETTINGS=../configuration/development.py python -m unittest"
