"""empty message

Revision ID: 245f56ce1a42
Revises: c9c271e02577
Create Date: 2016-10-05 16:38:10.835139

"""

# revision identifiers, used by Alembic.
revision = '245f56ce1a42'
down_revision = 'c9c271e02577'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_uid', sa.String(length=100), nullable=False),
    sa.Column('pdf', sa.Text(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'interrupted', 'finished', 'stopped'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_uid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computation')
    ### end Alembic commands ###
