"""empty message

Revision ID: a0e464571967
Revises: 9437851abb33
Create Date: 2016-10-25 11:55:33.000690

"""

# revision identifiers, used by Alembic.
revision = 'a0e464571967'
down_revision = '9437851abb33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_job_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('create_job_progress')
    ### end Alembic commands ###
